### PR TITLE
fixed serial connection issues, full repl in win

### PR DESCRIPTION
**Pull request by jmporter**

### CODE REVIEW

**Comment by jmporter** [comment]
Fixed the two most critical bugs that make shell49 difficult to work with for students.  As far as I can tell serial connection issue has been resolved. No need to even unplug microcontroller after a fresh flash.
  
REPL has full functionality in windows. Backspace, Del, Arrow Keys, Home, and End are all functional.

**Comment by bboser** [comment]
Thanks for these fixes. Merged without further review (I've switched to using jupyter for programming MCUs).

**Comment by bboser** [comment]
Hi Jared,

I've merged your changes. Many thanks!

One more thing to do: update PyPi.
I no longer have a working repo. Could clone, I suppose, but if you don't
mind I just add you as a maintainer on PyPi. For that I need your PyPi
login. Ok?

Thanks,
Bernhard

**Comment by jmporter** [comment]
Hi Professor,

I can take care of the update.
I created a PyPi account with the username: jmporter

Thanks,
Jared

**Comment by bboser** [comment]
You are now an owner of that repo.

Bernhard

**Pull request merged**
